name: 'Test'
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - main
  create:

jobs:
  test: # make sure the action works on a clean machine without building
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v3
      - name: Create a release deaft for a version tag
        id: create-release-draft
        uses: ./
      - name: Print the URL of the release draft
        run: echo ${{ steps.create-release-draft.outputs.release-url }}